name: unsup3d
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - cffi=1.14.0=py37hd463f26_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - cloudpickle=1.3.0=py_0
  - cryptography=2.8=py37hb09aad4_2
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py37h516909a_0
  - dask-core=2.14.0=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - expat=2.2.9=he1b5a44_2
  - ffmpeg=4.1.3=h167e202_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.1=he06d7ca_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.58.3=py37he00f558_1003
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.5=hd3a4fd2_1002
  - graphite2=1.3.13=he1b5a44_1001
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - harfbuzz=2.4.0=h37c48d4_1
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=58.2=hf484d3e_1000
  - idna=2.9=py_1
  - imageio=2.8.0=py_0
  - imageio-ffmpeg=0.4.1=py_0
  - jasper=1.900.1=h07fcdf6_1006
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.2.0=py37h99015e2_0
  - lame=3.100=h14c3975_1001
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=14_openblas
  - liblapacke=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_1
  - libprotobuf=3.11.4=h8b12597_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - lz4-c=1.8.3=he1b5a44_1001
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - moviepy=1.0.1=py_0
  - ncurses=6.2=he6710b0_0
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.4=py_1
  - numpy=1.18.1=py37h8960a57_1
  - olefile=0.46=py_0
  - opencv=4.1.1=py37ha799480_1
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1f=h516909a_0
  - pcre=8.44=he1b5a44_0
  - pillow=5.3.0=py37h00a061d_1000
  - pip=20.0.2=py37_1
  - pixman=0.38.0=h516909a_1003
  - proglog=0.1.9=py_0
  - protobuf=3.11.4=py37h3340039_1
  - pthread-stubs=0.4=h14c3975_1001
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py37hcca6a23_4
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.7=hcf32534_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pywavelets=1.1.1=py37hc1659b7_0
  - pyyaml=5.3.1=py37h8f50634_0
  - qt=5.9.7=h52cfd70_2
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=pyh8c360ce_2
  - scikit-image=0.16.2=py37hb3f55d8_0
  - scipy=1.4.1=py37ha3d9a3c_2
  - setuptools=46.1.3=py37_0
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.14.0=py_1
  - sqlite=3.31.1=h7b6447c_0
  - tensorboardx=2.0=py_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37h8f50634_1
  - tqdm=4.45.0=pyh9f0ad1d_0
  - urllib3=1.25.7=py37hc8dfbb8_1
  - wheel=0.34.2=py37_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - yaml=0.2.2=h516909a_1
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h3b9ef0a_2
